package hello;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller  // This means that this class is a Controller
@RequestMapping("/demo")  // This means URL's start with /demo (after Application path)
public class MainController {
	
	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private CustomerRepository customerRepository;
	
	
	@GetMapping("/add")
	public @ResponseBody String addNewUser(@RequestParam String firstName, @RequestParam String lastName, @RequestParam String productPurchased){
		
		Customer customer = new Customer();
	    customer.setFirstName(firstName);
	    customer.setLastName(lastName);
	    customer.setProductPurchased(productPurchased);
	    
	    customerRepository.save(customer);
	    return "Saved";
	}
	
	@GetMapping("/all")
	public @ResponseBody Iterable<Customer> getAllUsers(){
		return customerRepository.findAll();
	}	

}
